# ✅ Solutions — Session 2: Reshaping and Indexing

Worked solutions to all five exercises plus the mini project.

## Exercise 1 (Easy) — 16 elements into a 4×4 matrix

In [1]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Exercise 2 (Easy) — the middle element of a 3×3

Row 1, column 1 (0-indexed) holds the value 4.

In [2]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print("middle element:", arr[1, 1])   # 4

[[0 1 2]
 [3 4 5]
 [6 7 8]]
middle element: 4


## Exercise 3 (Medium) — last row, first column, and the center 3×3

In [3]:
m = np.arange(25).reshape(5, 5)
print("full matrix:\n", m)

print("\n(a) last row:      ", m[-1, :])
print("(b) first column:   ", m[:, 0])
print("(c) center 3x3:\n", m[1:4, 1:4])

full matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

(a) last row:       [20 21 22 23 24]
(b) first column:    [ 0  5 10 15 20]
(c) center 3x3:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


## Exercise 4 (Medium) — why `np.arange(10).reshape(3, 3)` fails

The original array has **10** elements, but a `(3, 3)` shape needs
`3 × 3 = 9`. Because 10 ≠ 9, NumPy raises a `ValueError`: the number of
elements must be conserved by a reshape.

In [4]:
try:
    np.arange(10).reshape(3, 3)
except ValueError as e:
    print("ValueError:", e)

ValueError: cannot reshape array of size 10 into shape (3,3)


## Exercise 5 (Advanced, conceptual) — read vs. mutate

- **Read only, fastest:** `reshape(-1)` or `ravel()`. Both return a *view*
  and avoid copying data, so they are essentially free.
- **Mutate without touching the original:** `flatten()`. It always returns an
  independent *copy*, so writes to the result cannot leak back into the
  source array.

In [5]:
original = np.arange(6).reshape(2, 3)

view = original.ravel()          # shares memory
copy = original.flatten()        # independent

view[0] = 111
copy[0] = 222

print("original after view write: ", original)   # changed
print("original after copy write: ", original)   # unchanged by the copy

original after view write:  [[111   1   2]
 [  3   4   5]]
original after copy write:  [[111   1   2]
 [  3   4   5]]


## 🚀 Mini Project — Matrix Cropper

In [6]:
def crop(matrix, row_start, row_end, col_start, col_end):
    # Extract a rectangular sub-region using 2D slicing
    return matrix[row_start:row_end, col_start:col_end]

matrix = np.arange(36).reshape(6, 6)
print("Full matrix:\n", matrix)

top_left = crop(matrix, 0, 2, 0, 2)
bottom_right = crop(matrix, 3, 6, 3, 6)

print("\nTop-left 2x2:\n", top_left)
print("Bottom-right 3x3:\n", bottom_right)

# Confirm flatten() copy safety
flat_copy = top_left.flatten()
flat_copy[0] = -1
print("\nFlattened copy modified:", flat_copy)
print("Original matrix unaffected:\n", matrix)

Full matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Top-left 2x2:
 [[0 1]
 [6 7]]
Bottom-right 3x3:
 [[21 22 23]
 [27 28 29]
 [33 34 35]]

Flattened copy modified: [-1  1  6  7]
Original matrix unaffected:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
