# Session 2 — Reshaping, Views, and Indexing

Runnable code for the **Build It** and **Experiment** sections. Run each cell top to bottom.

## 1. Build It — Core Code

In [1]:
import numpy as np

# --- 1. Reshape a 1D array into a matrix ---
a = np.arange(12)
b = a.reshape(3, 4)
print("Original 1D array:", a)
print("Reshaped to 3x4:\n", b)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
# --- 2. Flatten it back to 1D three different ways ---
flat_via_reshape = b.reshape(-1)
flat_via_ravel = b.ravel()
flat_via_flatten = b.flatten()

print("\nreshape(-1):", flat_via_reshape)
print("ravel():", flat_via_ravel)
print("flatten():", flat_via_flatten)


reshape(-1): [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
# --- 3. Demonstrate the view vs copy difference ---
view_arr = b.ravel()       # a VIEW: shares memory with b (when possible)
copy_arr = b.flatten()     # a COPY: fully independent

view_arr[0] = 999          # mutate the view
copy_arr[0] = -999         # mutate the copy

print("\nAfter mutating the view, original b (may change):\n", b)
print("copy_arr is independent, original b is unaffected by copy_arr changes")


After mutating the view, original b (may change):
 [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
copy_arr is independent, original b is unaffected by copy_arr changes


In [4]:
# --- 4. 1D indexing/slicing ---
c = np.arange(5, 9)  # [5, 6, 7, 8]
print("\nc:", c)
print("c[0]:", c[0])
print("c[1]:", c[1])
print("c[2:]:", c[2:])
print("c[-3:-1]:", c[-3:-1])
print("c[2:4]:", c[2:4])


c: [5 6 7 8]
c[0]: 5
c[1]: 6
c[2:]: [7 8]
c[-3:-1]: [6 7]
c[2:4]: [7 8]


In [5]:
# --- 5. 2D indexing/slicing ---
d = np.arange(12).reshape(3, 4)
print("\nd:\n", d)
print("d[0]        (row 0)          :", d[0])
print("d[0, 1]     (row 0, col 1)   :", d[0, 1])
print("d[0, :]     (row 0, all cols):", d[0, :])
print("d[:, 1]     (all rows, col 1):", d[:, 1])
print("d[1, 1:]    (row 1, col 1+)  :", d[1, 1:])
print("d[:, -2:]   (all rows, last 2 cols):\n", d[:, -2:])
print("d[2, 0:2]   (row 2, cols 0-1):", d[2, 0:2])


d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
d[0]        (row 0)          : [0 1 2 3]
d[0, 1]     (row 0, col 1)   : 1
d[0, :]     (row 0, all cols): [0 1 2 3]
d[:, 1]     (all rows, col 1): [1 5 9]
d[1, 1:]    (row 1, col 1+)  : [5 6 7]
d[:, -2:]   (all rows, last 2 cols):
 [[ 2  3]
 [ 6  7]
 [10 11]]
d[2, 0:2]   (row 2, cols 0-1): [8 9]


## 2. Experiment

In [6]:
# Experiment 1: reshape fails if element counts don't match
a = np.arange(12)
try:
    a.reshape(5, 5)   # 25 != 12 -> raises ValueError
except ValueError as e:
    print("Reshape error:", e)

Reshape error: cannot reshape array of size 12 into shape (5,5)


In [7]:
# Experiment 2: prove ravel() shares memory, flatten() does not
b = np.arange(6).reshape(2, 3)
r = b.ravel()
f = b.flatten()

r[0] = 100
f[0] = 200

print("b after modifying ravel():\n", b)
print("b after modifying flatten() copy:\n", b)

b after modifying ravel():
 [[100   1   2]
 [  3   4   5]]
b after modifying flatten() copy:
 [[100   1   2]
 [  3   4   5]]


In [8]:
# Experiment 3: small vs large 2D slices
big = np.arange(100).reshape(10, 10)
print("Single element:", big[5, 5])
print("Whole row:", big[5, :])
print("Whole column:", big[:, 5])
print("Sub-block (rows 2-4, cols 2-4):\n", big[2:5, 2:5])

Single element: 55
Whole row: [50 51 52 53 54 55 56 57 58 59]
Whole column: [ 5 15 25 35 45 55 65 75 85 95]
Sub-block (rows 2-4, cols 2-4):
 [[22 23 24]
 [32 33 34]
 [42 43 44]]


In [9]:
# Experiment 4: negative slicing on 2D arrays
print("Last 2 rows, last 2 cols:\n", big[-2:, -2:])

Last 2 rows, last 2 cols:
 [[88 89]
 [98 99]]


## 3. Mini Project — Matrix Cropper

In [10]:
def crop(matrix, row_start, row_end, col_start, col_end):
    # Extract a rectangular sub-region using 2D slicing
    return matrix[row_start:row_end, col_start:col_end]

matrix = np.arange(36).reshape(6, 6)
print("Full matrix:\n", matrix)

top_left = crop(matrix, 0, 2, 0, 2)
bottom_right = crop(matrix, 3, 6, 3, 6)

print("\nTop-left 2x2:\n", top_left)
print("Bottom-right 3x3:\n", bottom_right)

# Confirm flatten() copy safety
flat_copy = top_left.flatten()
flat_copy[0] = -1
print("\nFlattened copy modified:", flat_copy)
print("Original matrix unaffected:\n", matrix)

Full matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Top-left 2x2:
 [[0 1]
 [6 7]]
Bottom-right 3x3:
 [[21 22 23]
 [27 28 29]
 [33 34 35]]

Flattened copy modified: [-1  1  6  7]
Original matrix unaffected:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
