# ✅ Solutions — Session 5: Random Sampling and File I/O

Worked solutions to all five exercises plus the mini project.

## Exercise 1 (Easy) — 20 Normal samples (mean 50, std 10)

In [1]:
import numpy as np

np.random.seed(0)
samples = np.random.normal(50, 10, size=20)
print("samples:", samples)
print("sample mean:", samples.mean())
print("sample std: ", samples.std())

samples: [67.64052346 54.00157208 59.78737984 72.40893199 68.6755799  40.2272212
 59.50088418 48.48642792 48.96781148 54.10598502 51.44043571 64.54273507
 57.61037725 51.21675016 54.43863233 53.33674327 64.94079073 47.94841736
 53.13067702 41.45904261]
sample mean: 55.69334592945635
sample std:  8.501828003994659


## Exercise 2 (Easy) — count Uniform samples above 0.5

In [2]:
np.random.seed(1)
u = np.random.uniform(0, 1, size=15)
print("samples:", u)
print("above 0.5:", u[u > 0.5])
print("count:", (u > 0.5).sum())

samples: [4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
 2.04452250e-01 8.78117436e-01 2.73875932e-02]
above 0.5: [0.72032449 0.53881673 0.6852195  0.87811744]
count: 4


## Exercise 3 (Medium, coding) — save/load a 4×4 matrix via `.npz`

In [3]:
np.random.seed(2)
matrix = np.random.normal(0, 1, size=(4, 4))
np.savez("matrix.npz", matrix=matrix)

reloaded = np.load("matrix.npz")["matrix"]
print("identical?", np.array_equal(matrix, reloaded))
print(reloaded)

identical? True
[[-0.41675785 -0.05626683 -2.1361961   1.64027081]
 [-1.79343559 -0.84174737  0.50288142 -1.24528809]
 [-1.05795222 -0.90900761  0.55145404  2.29220801]
 [ 0.04153939 -1.11792545  0.53905832 -0.5961597 ]]


## Exercise 4 (Medium) — dtype after a CSV round-trip

Values are written as text, and text has no notion of "integer", so
`np.loadtxt` reads everything back as `float64`.

In [4]:
floats = np.array([1.5, 2.25, 3.125, 4.75, 5.0])
np.savetxt("floats.csv", floats, delimiter=",")
reloaded_floats = np.loadtxt("floats.csv", delimiter=",")
print("original dtype:", floats.dtype)
print("reloaded dtype:", reloaded_floats.dtype)

original dtype: float64
reloaded dtype: float64


## Exercise 5 (Advanced, conceptual) — why the sample converges

Each draw is an independent, identically-distributed sample from the same
distribution. Averaging more such draws cancels individual deviations, so the
average's spread shrinks like `1/sqrt(n)` around the true mean. This is the
**Law of Large Numbers**, and it is why larger samples estimate the true
`mean`/`std` more tightly.

In [5]:
np.random.seed(3)
for n in (10, 100, 10_000, 1_000_000):
    s = np.random.normal(50, 10, size=n)
    print(f"n={n:>9}: mean={s.mean():7.3f}  std={s.std():6.3f}")

n=       10: mean= 48.595  std= 8.664
n=      100: mean= 49.169  std=10.565
n=    10000: mean= 49.718  std= 9.950
n=  1000000: mean= 50.024  std= 9.984


## 🚀 Mini Project — Simulate, Persist, and Round-Trip a Dataset

In [6]:
import os

np.random.seed(7)
true_mean, true_std = 25.0, 2.5
sensor_readings = np.random.normal(true_mean, true_std, size=1000)

print("True mean/std:", true_mean, true_std)
print("Sample mean/std:", sensor_readings.mean(), sensor_readings.std())

np.savez("sensor_data.npz", sensor_readings=sensor_readings)
reloaded = np.load("sensor_data.npz")["sensor_readings"]
print("\n.npz round-trip identical?", np.array_equal(sensor_readings, reloaded))

subset = sensor_readings[:20]
np.savetxt("sensor_subset.csv", subset, header="reading", delimiter=",")
reloaded_subset = np.loadtxt("sensor_subset.csv", delimiter=",")
print("\nReloaded CSV subset:", reloaded_subset)
print("Reloaded dtype:", reloaded_subset.dtype)

True mean/std: 25.0 2.5
Sample mean/std: 24.92881243357207 2.406149174232953

.npz round-trip identical? True

Reloaded CSV subset: [29.22631426 23.83515657 25.08205041 26.01879071 23.02769243 25.00516393
 24.99777404 20.61318923 27.54414501 26.50124629 23.43642757 24.57112935
 26.26324844 24.34660896 24.3931273  21.36689647 26.38645078 25.30970226
 25.68614981 21.18368867]
Reloaded dtype: float64


In [7]:
# Clean up generated files
for f in ("matrix.npz", "floats.csv", "sensor_data.npz", "sensor_subset.csv"):
    if os.path.exists(f):
        os.remove(f)
print("Cleaned up generated files.")

Cleaned up generated files.
