# ✅ Solutions — Session 3: Boolean Indexing, Operations, and Broadcasting

Worked solutions to all five exercises plus the mini project.

## Exercise 1 (Easy) — elements divisible by 4

In [1]:
import numpy as np

arr = np.arange(20)
print(arr[arr % 4 == 0])

[ 0  4  8 12 16]


## Exercise 2 (Easy) — less than 3 OR greater than 15

Use the element-wise OR operator `|` and parenthesize each condition.

In [2]:
print(arr[(arr < 3) | (arr > 15)])

[ 0  1  2 16 17 18 19]


## Exercise 3 (Medium) — element-wise vs. matrix product

In [3]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9, 18).reshape(3, 3)

print("a:\n", a)
print("b:\n", b)
print("\nElement-wise (a * b):\n", a * b)
print("\nMatrix product (a @ b):\n", a @ b)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b:
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]

Element-wise (a * b):
 [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]

Matrix product (a @ b):
 [[ 42  45  48]
 [150 162 174]
 [258 279 300]]


## Exercise 4 (Medium) — predict the broadcast shape

`(5, 1)` and `(1, 4)` align to `(5, 4)`: the column stretches across 4
columns and the row stretches down 5 rows.

In [4]:
col = np.arange(5).reshape(5, 1)
row = np.arange(4).reshape(1, 4)
print("col shape:", col.shape, "row shape:", row.shape)
print("sum shape:", (col + row).shape)
print(col + row)

col shape: (5, 1) row shape: (1, 4)
sum shape: (5, 4)
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


## Exercise 5 (Advanced, conceptual) — why one fails, one succeeds

Broadcasting aligns shapes **from the right**:

- `(3,)` and `(2,)` → compare `3` and `2`: not equal and neither is `1`,
  so NumPy raises `ValueError`.
- `(2, 3)` and `(3,)` → align as `(2, 3)` vs `(1, 3)`: the trailing `3`
  matches, and the leading `1` is stretched to `2` → result shape `(2, 3)`.

In [5]:
try:
    np.array([1, 2, 3]) + np.array([1, 2])
except ValueError as e:
    print("(3,) + (2,) ->", e)

result = np.array([[1, 2, 3], [4, 5, 6]]) + np.array([1, 2, 3])
print("(2,3) + (3,) -> shape", result.shape)
print(result)

(3,) + (2,) -> operands could not be broadcast together with shapes (3,) (2,) 
(2,3) + (3,) -> shape (2, 3)
[[2 4 6]
 [5 7 9]]


## 🚀 Mini Project — Grade Filter and Curve

In [6]:
np.random.seed(42)
scores = np.random.randint(40, 101, size=20)
print("Scores:", scores)

at_risk = scores[scores < 60]
print("\nAt-risk scores (<60):", at_risk, "| count:", at_risk.size)

mid_range = scores[(scores >= 70) & (scores <= 85)]
print("Scores between 70-85:", mid_range)

curved = np.minimum(scores + 5, 100)
print("\nCurved scores (capped at 100):", curved)

normalized_scores = (scores - scores.mean()) / scores.std()
print("\nNormalized scores:", normalized_scores)

Scores: [ 78  91  68  54  82  47 100  60  78  97  58  62  50  50  63  92  75  79
  63  42]

At-risk scores (<60): [54 47 58 50 50 42] | count: 6
Scores between 70-85: [78 82 78 75 79]

Curved scores (capped at 100): [ 83  96  73  59  87  52 100  65  83 100  63  67  55  55  68  97  80  84
  68  47]

Normalized scores: [ 0.50623852  1.27595792 -0.08585332 -0.91478189  0.74307526 -1.32924618
  1.80884057 -0.55952679  0.50623852  1.63121302 -0.67794516 -0.44110842
 -1.15161863 -1.15161863 -0.38189924  1.3351671   0.32861097  0.56544771
 -0.38189924 -1.6252921 ]
