# Session 3 — Boolean Indexing, Operations & Broadcasting

Runnable code for the **Build It** and **Experiment** sections. Run each cell top to bottom.

## 1. Build It — Core Code

In [1]:
import numpy as np

# ---------- 1. Boolean indexing ----------
a = np.arange(12).reshape(3, 4)
print("a:\n", a)

mask = a < 5
print("\nmask (a < 5):\n", mask)
print("a[a < 5]:", a[mask])

# Storing a condition separately for readability
condition = a >= 3
print("a[a >= 3]:", a[condition])

# Combining conditions: parentheses are mandatory
print("a[(a > 2) & (a < 11)]:", a[(a > 2) & (a < 11)])
print("a[(a < 2) | (a % 3 == 0)]:", a[(a < 2) | (a % 3 == 0)])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

mask (a < 5):
 [[ True  True  True  True]
 [ True False False False]
 [False False False False]]
a[a < 5]: [0 1 2 3 4]
a[a >= 3]: [ 3  4  5  6  7  8  9 10 11]
a[(a > 2) & (a < 11)]: [ 3  4  5  6  7  8  9 10]
a[(a < 2) | (a % 3 == 0)]: [0 1 3 6 9]


In [2]:
# ---------- 2. Element-wise operations ----------
v1 = np.array([1, 3, 2, 7])
v2 = np.array([4, 1, 1, 3])

print("\nv1 + v2:", v1 + v2, "| np.add:", np.add(v1, v2))
print("v1 * v2:", v1 * v2, "| np.multiply:", np.multiply(v1, v2))
print("v1 ** v2:", v1 ** v2, "| np.power:", np.power(v1, v2))


v1 + v2: [ 5  4  3 10] | np.add: [ 5  4  3 10]
v1 * v2: [ 4  3  2 21] | np.multiply: [ 4  3  2 21]
v1 ** v2: [  1   3   2 343] | np.power: [  1   3   2 343]


In [3]:
# ---------- 3. Matrix multiplication vs element-wise multiplication ----------
x = np.array([[1, 2], [3, 4]])
y = np.array([[3, 4], [1, 5]])

print("\nElement-wise x * y:\n", x * y)
print("True matrix multiplication x @ y:\n", x @ y)
print("np.matmul(x, y):\n", np.matmul(x, y))


Element-wise x * y:
 [[ 3  8]
 [ 3 20]]
True matrix multiplication x @ y:
 [[ 5 14]
 [13 32]]
np.matmul(x, y):
 [[ 5 14]
 [13 32]]


In [4]:
# ---------- 4. Broadcasting ----------
scalar_times_vector = np.array([1, 2, 3]) * 2
print("\nvector * scalar (broadcast):", scalar_times_vector)

col = np.array([0, 10, 20, 30]).reshape(4, 1)  # shape (4, 1)
row = np.array([0, 1, 2])                       # shape (3,)
print("Broadcast (4,1) + (3,):\n", col + row)


vector * scalar (broadcast): [2 4 6]
Broadcast (4,1) + (3,):
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [5]:
# ---------- 5. Real-world broadcasting: normalization ----------
data = np.array([1, 2, 3, 4, 5])
normalized = (data - data.mean()) / data.std()
print("\nOriginal data:", data)
print("Normalized data:", normalized)
print("New mean (~0):", normalized.mean())
print("New std  (~1):", normalized.std())


Original data: [1 2 3 4 5]
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
New mean (~0): 0.0
New std  (~1): 0.9999999999999999


## 2. Experiment

In [6]:
# Experiment 1: forgetting parentheses in combined conditions raises an error
a = np.arange(10)
try:
    result = a[a > 2 & a < 8]   # missing parentheses -> operator precedence bug
except Exception as e:
    print("Error without parentheses:", type(e).__name__, e)

print("Correct version:", a[(a > 2) & (a < 8)])

Error without parentheses: ValueError The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Correct version: [3 4 5 6 7]


In [7]:
# Experiment 2: element-wise vs matrix multiplication on the SAME matrices
x = np.array([[2, 0], [0, 2]])
y = np.array([[1, 2], [3, 4]])
print("Element-wise x * y:\n", x * y)
print("Matrix mult   x @ y:\n", x @ y)   # very different result!

Element-wise x * y:
 [[2 0]
 [0 8]]
Matrix mult   x @ y:
 [[2 4]
 [6 8]]


In [8]:
# Experiment 3: incompatible broadcasting shapes
try:
    a3 = np.array([1, 2, 3])
    b3 = np.array([1, 2])
    print(a3 + b3)
except ValueError as e:
    print("Broadcast error:", e)

Broadcast error: operands could not be broadcast together with shapes (3,) (2,) 


In [9]:
# Experiment 4: broadcasting a (1,4) row against a (3,1) column
row = np.array([[1, 2, 3, 4]])          # shape (1, 4)
col = np.array([[10], [20], [30]])      # shape (3, 1)
print("Row + Col broadcast result, shape:", (row + col).shape)
print(row + col)

Row + Col broadcast result, shape: (3, 4)
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [10]:
# Experiment 5: normalization on a larger, more skewed dataset
big_data = np.array([10, 12, 13, 12, 100])  # one outlier
print("Normalized (with outlier):", (big_data - big_data.mean()) / big_data.std())

Normalized (with outlier): [-0.5493657  -0.49273006 -0.46441224 -0.49273006  1.99923805]


## 3. Mini Project — Grade Filter and Curve

In [11]:
np.random.seed(42)  # reproducibility
scores = np.random.randint(40, 101, size=20)
print("Scores:", scores)

# At-risk students (boolean indexing)
at_risk = scores[scores < 60]
print("\nAt-risk scores (<60):", at_risk, "| count:", at_risk.size)

# Students scoring between 70 and 85 inclusive (combined condition)
mid_range = scores[(scores >= 70) & (scores <= 85)]
print("Scores between 70-85:", mid_range)

# Curve every score by +5, capped at 100 (broadcasting + np.minimum)
curved = np.minimum(scores + 5, 100)
print("\nCurved scores (capped at 100):", curved)

# Normalize original scores (broadcasting)
normalized_scores = (scores - scores.mean()) / scores.std()
print("\nNormalized scores:", normalized_scores)

Scores: [ 78  91  68  54  82  47 100  60  78  97  58  62  50  50  63  92  75  79
  63  42]

At-risk scores (<60): [54 47 58 50 50 42] | count: 6
Scores between 70-85: [78 82 78 75 79]

Curved scores (capped at 100): [ 83  96  73  59  87  52 100  65  83 100  63  67  55  55  68  97  80  84
  68  47]

Normalized scores: [ 0.50623852  1.27595792 -0.08585332 -0.91478189  0.74307526 -1.32924618
  1.80884057 -0.55952679  0.50623852  1.63121302 -0.67794516 -0.44110842
 -1.15161863 -1.15161863 -0.38189924  1.3351671   0.32861097  0.56544771
 -0.38189924 -1.6252921 ]
